### ISSUE TITLE
Cannot process ##Headings

### ISSUE THREAD

**Issue by Hunter-Github** [celsomiranda/hexo-renderer-markdown-it#11] opened 2015-04-15 23:41 UTC
Default `hexo-renderer-marked` converts `##Headings` to `<h2 id="Headings">Headings</h2>`

`hexo-renderer-markdown-it` doesn't replicate this behavior, and has `<h2 ...>##Headings...` instead.

...with an otherwise unremarkable `_config.yml`:

     markdown:
         render:
             breaks: false
             html:   true
        plugins:
             - markdown-it-footnote
             - markdown-it-sup
             - markdown-it-sub

**Comment by celsomiranda** [comment] 2015-04-16 08:25
My research tells me this comes from upstream. Although I can't tell you if this is a bug, or if it's by design.

If you want, you can open [an issue  here](https://github.com/markdown-it/markdown-it/issues).

That said. This renderer aims to bring `markdown-it` support with a few of it's plugins (you can always create a request if you want a specific plugin to be included). It's not the aim of this project to be fully compatible with `marked`, which adds features that aren't in any spec.

John Grubber's markdown spec and CommonMark define the hash headlines as having a space between the `#`  and the heading text, so as far as I know, that's something that marked maybe shouldn't be doing.

I'm closing this, but I'll re-open if the `markdown-it` devs change the behaviour of their parser.

**Closed by celsomiranda** 2015-04-16 08:25 UTC

**Comment by Hunter-Github** [comment] 2015-04-17 09:31
Okay, fine by me. Found the relevant reference in the CommonMark spec: http://spec.commonmark.org/0.18/#atx-headers

**Comment by celsomiranda** [comment] 2015-04-17 09:33
Thanks. :+1:
